site_name: Momentum Curriculum
nav:
  - Home: README.md
  - Skills: skills.md
  - Phase One:
      - Week 1:
          - "Establishing the Community of the Classroom": "community.md"
          - "1. Command Line and Git": "front-end/command-line-and-git/lesson.md"
          - "2. HTML": "front-end/html/lesson.md"
